export enum UserRole {
  SUPER_ADMIN = 'SUPER_ADMIN',
  OWNER = 'OWNER',
  ADMIN = 'ADMIN',
  MANAGER = 'MANAGER',
  AGENT = 'AGENT',
  VIEWER = 'VIEWER',
  MARKETER = 'MARKETER',
  BUYER = 'BUYER',
  MARKETPLACE_ADMIN = 'MARKETPLACE_ADMIN',
}
